<?php

namespace App\Views;

use App\App;

class Navigation extends \Core\View
{
    public function __construct()
    {
        parent::__construct($this->generate());
    }

    public function generate()
    {
        $nav = [App::$router::getUrl('index') => 'Home'];

        if (App::$session->getUser()) {
            return $nav + [
                    App::$router::getUrl('add') => 'Add',
                    App::$router::getUrl('list') => 'Edit',
                    App::$router::getUrl('logout') => 'Logout',
                ];
        } else {
            return $nav + [
                    App::$router::getUrl('register') => 'Register',
                    App::$router::getUrl('login') => 'Login',
                ];
        }
    }

    function render($template_path = ROOT . '/app/templates/nav.tpl.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }
}