<?php

namespace App\Views;

use App\App;

class Navigation extends \Core\View
{
    public function __construct()
    {
        parent::__construct($this->generate());
    }

    public function generate()
    {
        $nav = ['/index.php' => 'Home'];

        if (App::$session->getUser()) {
            return $nav + [
                    '/Admin/add.php' => 'Add',
                    '/logout.php' => 'Logout',
                ];
        } else {
            return $nav + [
                    '/register.php' => 'Register',
                    '/login.php' => 'Login',
                ];
        }
    }

    function render($template_path = ROOT . '/app/templates/nav.tpl.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }
}